tutorial: Add some precisions in the first lessons
chairemobilite/transition-docs pull request #5
Opened 2023-07-16 15:55 UTC by tahini

Some revisions as per Hubert's comments

2023-07-16 16:52 UTC, kaligrafy requested changes

2023-07-16 16:52 UTC, kaligrafy commented on tutorial/README.md
> +Many transit feeds can be easily found in the [Open Mobility data](https://transitfeeds.com/) website, but the most up to date versions are recorded in the [Mobility Database catalogs](https://databa
I would prefer Montreal transit agency instead is society which sound weird in English

2023-07-16 17:01 UTC, greenscientist commented on tutorial/README.md
> +This tutorial will guide you through the first steps of using [Transition](http://transition.city) and help you discover what can be achieved with it. Transition is a web-based open source platform u
Maybe: "You can create, import and edit..." ?

2023-07-16 17:03 UTC, greenscientist reviewed
Just a few small comment, feel free to ignore if you want.

2023-07-16 17:03 UTC, greenscientist commented on tutorial/README.md
> +But at this point, there should be data available in Transition! You can see what was just imported, navigate the lines and paths, view the stop nodes, etc.
Do we navigate the line or we navigate the interface and scroll the map and see the various line and path?

2023-07-16 18:20 UTC, kaligrafy approved these changes

2023-07-17 12:39 UTC, greenscientist approved these changes

2023-07-17 13:14 UTC, merged